name: tag-commit
description: Tag the latest commit with the version read from 'bump-my-version'

branding:
  icon: activity
  color: gray-dark

inputs:
  repository:
    description: Repository Owner and Repository Name
    default: ${{ github.repository }}
  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v6

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7

    - name: Install 'bump-my-version'
      shell: bash
      run: uv tool install bump-my-version

    - name: Run 'script.py'
      shell: bash
      run: uv run script.py
